### ISSUE TITLE
Enable viewing reports through "lenses"

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/httparchive.org#40]
**Goal:** Provide a mechanism for users to apply one or more "lenses" through which to view the HTTP Archive reports. These lenses effectively filter the set of websites to a subset that match some condition. For example, all websites that run on WordPress.

**Strategy:**

- [x] 1. write a query that generates a list of URLs/pages to act as the whitelist for the lens
- [x] 2. alter the report generation script to integrate that whitelist of pages with each metrics' timeseries and histogram queries
  - [x] 2a. optionally replace YYYY_MM_DD placeholders in whitelist query with report date
  - [x] 2b. save the lens results to an identifiable subdirectory on the gs:// CDN
- [x] 3. build a UI to enable the addition/removal of a lens
  - [x] 3a. provide a way to persist the selected lens across page views
  - [x] 3b. alter the report UI to make clear when a lens has been applied
  - [x] 3c. provide URL shortcuts (eg wordpress.httparchive.org or httparchive.org/wordpress)
- [x] 4. alter the data visualization scripts to pull data from the correct lens on the CDN

**Stretch goals:**

- [ ] 5. support multiple concurrent lenses for side-by-side comparison
  - [ ] 5a. in the lens selector UI
  - [ ] 5b. in the data visualization UI

**Comment by rviscomi** [comment]
Prototyping this with a WordPress lens.

(1) is solved by querying the `httparchive.wappalyzer.wordpress` table, limited to the particular date/client of the report.

Made progress on (2) with [this commit](https://github.com/rviscomi/bigquery/commit/28e6e968ef200ea0735498c505c0e5f921792d76). It kinda works for some metrics. It's always joining using the `url` field, which doesn't do the expected behavior for metrics that query the requests table. For that we need to join on `request.page = detected.url`.

(2a) substitution is necessary. See script changes above.

(2b) is resolved by adding the query results to the GCS CDN in a new subdir under `/reports` that is the name of the lens. For example https://cdn.httparchive.org/reports/wordpress/bytesTotal.json is the timeseries of WordPress total bytes.

Skipping (3) for the prototype and manually adding the lens to the page via querystring param, eg `?lens=wordpress`.

Made progress on (4) with [this commit](https://github.com/rviscomi/beta.httparchive.org/commit/bb757ca612e0eefb9a7d57b1746613d4c20d8b71). As of now it just inserts whatever's in the lens param into the CDN url (see 2b note above). Invalid lenses will cause the CDN requests to fail, but these are not currently handled. There should ideally be some validation done in step (3).


To see it in action, here's the total bytes timeseries for WordPress:

![image](https://user-images.githubusercontent.com/1120896/39669287-d58670a2-50b5-11e8-825b-ce9a36f68544.png)

And the normal timeseries for reference:

![image](https://user-images.githubusercontent.com/1120896/39669291-e3f93282-50b5-11e8-9b4e-79fe4c6c509b.png)

Many interesting insights to be had already! I'll compile and share in the discuss.httparchive.org forum soon.

**Comment by rviscomi** [comment]
I've set up the `wordpress` lens subdomain. Try it out: https://wordpress.httparchive.org/reports/state-of-the-web

![image](https://user-images.githubusercontent.com/1120896/40943959-09c1a1b6-6821-11e8-92d8-1b5723467739.png)

All that works now is that the lens is enabled by default. Still need to fix some other issues around the report generation of the lens, so not all metrics are working yet.

**Comment by igrigorik** [comment]
Neat-o! Nice work Rick. 

https://wordpress.httparchive.org/reports/state-of-the-web#pctHttps is zero? Is this a bug?

Otherwise, scrubbing through all the reports.. The medians appear to be slightly higher across the board — hard to say what specific conclusion we should draw from that, but still interesting. 

Have you found any particular / interesting insights that have jumped out at you?

**Comment by rviscomi** [comment]
pctHttps is a known issue (see https://github.com/HTTPArchive/httparchive.org/issues/40#issuecomment-386849483 around querying requests).

I put together some interesting insights from this lens in my WordPress talk in Napa: https://www.slideshare.net/jrvis/the-state-of-performance-in-the-wordpress-ecosystem skip to slide 33

**Comment by igrigorik** [comment]
> pctHttps is a known issue (see #40 (comment) around querying requests).

I'm a little hazy on the issue still but sounds like you're already on it and it'll be resolved. 

> I put together some interesting insights from this lens in my WordPress talk in Napa: https://www.slideshare.net/jrvis/the-state-of-performance-in-the-wordpress-ecosystem skip to slide 33

Nice. Consistent with my takeaways so far. Couple of wishlist items:

- In your deck you compare medians, but I wonder how the overall distributions compare — do we see fatter tails, or different / other modes?
- CrUX data differences are super interesting and much more dramatic. Speaking of..
  - https://wordpress.httparchive.org/reports/chrome-ux-report?start=2018_04_01&end=latest — errors out for me. Presumably we'd need some extra plumbing to hook this up?

**Comment by rviscomi** [comment]
The pctHttps issue should be fixed now. See https://wordpress.httparchive.org/reports/state-of-the-web#pctHttps

You could drill down into the distribution by setting start==end in the date filter, eg https://wordpress.httparchive.org/reports/state-of-the-web?start=2018_05_01 (05_15 not yet available for WordPress) compared to https://httparchive.org/reports/state-of-the-web?start=2018_05_01

I think we should disable the CrUX report when a lens is enabled. The WP-detection used in the slides was a one-off analysis by @pmeenan in January and we don't know which origins are WP in the subsequent releases.

**Comment by igrigorik** [comment]
> The pctHttps issue should be fixed now. See https://wordpress.httparchive.org/reports/state-of-the-web#pctHttps

Nice! 👍 Great to see WP nudging slightly ahead of the broader web here.

> You could drill down into the distribution by setting start==end in the date filter, eg https://wordpress.httparchive.org/reports/state-of-the-web?start=2018_05_01 (05_15 not yet available for WordPress) compared to https://httparchive.org/reports/state-of-the-web?start=2018_05_01

Yep! Sorry, poor wording on my part.. I was suggesting that in future analysis/presentations, it might be worth considering looking at broader distribution to see if there are any notable differences other than just comparing medians.

> I think we should disable the CrUX report when a lens is enabled. The WP-detection used in the slides was a one-off analysis by @pmeenan in January and we don't know which origins are WP in the subsequent releases.

This should be a non-problem once we migrate over to crawling CrUX origins next month, right? Or, come to think of it, there may be some merit to restricting the CrUX data we show on HA to overlap with the HA origins — that would also then enable us to look at WP/CrUX/Alexa intersection here, right?

**Comment by rviscomi** [comment]
Two new lenses added:

https://drupal.httparchive.org
https://magento.httparchive.org

Backfilling 2.5 years of histograms for each lens and metric, so not all of the old stuff is up yet but the latest data should all be there including all of the timeseries data.

Especially interesting to compare all of the lenses together! Eg total KB as of August 1:


URL | Lens | Desktop Total KB | Mobile Total KB
-- | -- | -- | --
https://httparchive.org/reports/state-of-the-web#bytesTotal | None | 1511.2 | 1253.9
https://drupal.httparchive.org/reports/state-of-the-web#bytesTotal | Drupal | 1814.2 | 1752.4
https://magento.httparchive.org/reports/state-of-the-web#bytesTotal | Magento | 2801.6 | 2658.7
https://wordpress.httparchive.org/reports/state-of-the-web#bytesTotal | WordPress | 1986.3 | 2077.7

_Magento what are you doing?!_

**Comment by rviscomi** [comment]
Closing this issue. We accomplished everything but the stretch goals (lens comparison), which we can track in a separate issue as needed.
